apiVersion: ENC[AES256_GCM,data:a8I=,iv:O3zZQEvUtQqzz+V70hK6dMYXGR5p4+8BP/yCbTL0tAs=,tag:ewtjdIRw37kYwsxbmg9ojA==,type:str]
kind: ENC[AES256_GCM,data:8bSjB2Xg,iv:23tLhuiaLHfTHN/TAMhE5A93d0LYk1b4JGA/jH3JQsg=,tag:K3h5D60AzEHcT5lTokrl1A==,type:str]
data:
    password: ENC[AES256_GCM,data:+P9BkXaDsefOZ/MWGxg/0Q==,iv:Rt6d6mI5CXFyQ+kw/yJp+mcBwyJR9mO52vXkIoKT29E=,tag:m5Ut6roFGu0P7ZfjFtxhlg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:0aRi2EjH4VKqbXSM/A==,iv:bRxPskhInlmPYMDzuiQt2dFn/8oXI4zhbGY3HQt6UWc=,tag:CrIR3vhuNavUB0t1aq4xhQ==,type:str]
    namespace: ENC[AES256_GCM,data:XFnTgRcCQ74NuxI=,iv:h88iyU+uq7HyBfaNg3tg9x3iyahFVxOKeO0EOzxaGZc=,tag:NnDbWew/XaOsOc6bJplHTA==,type:str]
type: ENC[AES256_GCM,data:wc2IA+VT,iv:p0HFCkoIVzu6W3rJVRFwN1yDrLfTsd/X64QOuBpe23o=,tag:3PdX0nB7/C6WSBYzOqn4mw==,type:str]
sops:
    lastmodified: "2026-01-16T17:54:16Z"
    mac: ENC[AES256_GCM,data:aJ343QlUPFK/BzWA/s488Z2wyVLtDeoaQFWbu2fy9m4K7+va+A1E1+2gYnIy0OsisDMP6XmzmoZOJ/Tp0yTV9xegBc3vDlbkKm19e4LzwLUyr0VG+GyBVV7UcSzF49gtUwikNGwSfsrsgrFrsQ+lLlv9p4ITnZrINZfEGdpiTPY=,iv:WtUNF8cgalhhwbljvUVMmbXqY2B7VHCBzQ74cOyqsdk=,tag:I4wKqNjafrEvJA36KPt8aA==,type:str]
    pgp:
        - created_at: "2026-01-16T17:54:16Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA8zGTYfuBl06AQ/8CDHyJ1n0AlltyETJq49bPK0JL1wSK1Xd2oGASCGRmqxr
            V/MI2tu15OAh0ceM8/OI1DAxq6ANt/YOQxm1FzITZvUawr4AURJPP1eP4w4TZpIK
            0eWCIUd3Kg+a+B8x9ajGKjNZPEhc522TCelDEVhYlhAk3qfQeH95TvYDbBYl1u0d
            yEhsUKVfw07KuINt6WMYA33ClSnadUErPwUg6wvZQnjTV1fsIICtVu36wJgCfjRj
            wePLEqj33xg2JZ9o/0qqFH2uHDP6H0l8xzwYKfmDq37rtuYJrBz7O9tiTKj5nz87
            b5WNlgQ9P61lKYUzM8GR1zCNpKAWG5AGyOgF+90U7BEMIGB5u1ryMwvkRdbuJBbG
            k7OgCoQCujAtOEiQOjMG/mmevDrkm8kdMxOfIN35axUuU/eCIG5aGIFzcXvEve2y
            Xw4YxARlCk7ZXyFS9MGTQB+X3rBxoJo8QeyMC/KxK1zi/nPLFiCjmYCkK6BzMvDL
            e5AQ0Lh7a3fwwkSxFf9J5Gkv+Zvg43C/7qkrl9vsjWNYDmMF3mVJ3HS57NdGLzFP
            iAa+QaLnLukkuUudxsBTBwoIrK8kaM4z7/KC+NiOnuv8l5ogvsDrEOB2qcmXFLcI
            wEJJRqP95YlZegoWFsP0WeaEYH8d4XVetlhzrYHz/RnIt4yW4nX8KzJDkOKPPonU
            ZgEJAhBb+bVBerg2sUgHBHNGqdSyk1EZ8j8Q8WrV3bWjKUd7bMZp+gGml1dsL0cm
            WcFAcSt4SE1S4SrRxqM9qzxvYbGQ4Rgzt25T3+LX+D5aEQUt5NXp0XAW9ypIBAlc
            phDcyTWdXA==
            =23DP
            -----END PGP MESSAGE-----
          fp: 51DECC40A0CA13D21FA6FCF3775783D61292D91E
    unencrypted_suffix: _unencrypted
    version: 3.11.0
