apiVersion: ENC[AES256_GCM,data:YCs=,iv:iNV3fiD+bKJebqrV/QAExtBdOLyFlB12Nl0/HXwNC3s=,tag:VkQZBRsfo5gpjAJzZj7fxw==,type:str]
kind: ENC[AES256_GCM,data:jz6HuLae,iv:hQRzI+NTjdVLjnWC5wHTMYgOQtVde3yYSDHMISWzbkk=,tag:W84lfC2y7oGF/qYbXQzvYA==,type:str]
data:
    password: ENC[AES256_GCM,data:t+q47suWjj1EkWvjFam8QA==,iv:u5qW/wcC31cL+4WNZiOo/0AcI/4vNZcfx+RXDZ7cs70=,tag:vLiZ7nBicd2k+tBJaBih8g==,type:str]
metadata:
    creationTimestamp: ENC[AES256_GCM,data:H1PyFaLFh4xL1SrjuzcNAP6bEaA=,iv:1Zo53VyBUbThgo+CP5p5BrYy1YjGJJb57gk26HkaKNU=,tag:89OvbfJVKlCXXLXe3BIGfg==,type:str]
    name: ENC[AES256_GCM,data:uP/9KcuDeipYxaknow==,iv:hMA6pHJdJ+Syjuo6aC+X2IVBAv8bfQ2ncwjkgzu/XKs=,tag:p5qo+k0iZ0QOP+UVn+XX5g==,type:str]
    namespace: ENC[AES256_GCM,data:5pdXGwbcKR5Sq2Q=,iv:Sj4PqfRBd1kZF+9tGQl4YpzPtmER9yuANVr/c7vPAOU=,tag:wJKbs6DsQTpkKraWpl2RCg==,type:str]
    resourceVersion: ENC[AES256_GCM,data:zqzgYsRzUGM=,iv:2/fjDUfKwZGtSmXOw7dq4ktw6ww8vBvlB3UW02/BOtY=,tag:Qd4F4sAtjZAWnQxbdZoEbg==,type:str]
    uid: ENC[AES256_GCM,data:pxe3o3msvFIhgmDagpsvwPJP9kslwD2JyvrVVyAwWOTUqF8I,iv:w0M18K5T8n5DN1irzGogPi9MdJetWmM59fxCP6EcLpA=,tag:g0/Qw1WwLlns9CkY9ujoog==,type:str]
type: ENC[AES256_GCM,data:L5jREMLv,iv:7WuSve6Tp5xiMkle+T+KY/72CjOnun1jIgnt6HOaTwE=,tag:4mzG3oviHlMUF5ULLbJgKg==,type:str]
sops:
    lastmodified: "2026-01-16T17:26:33Z"
    mac: ENC[AES256_GCM,data:66jcbx5Fvl2nVqlDHbJwu7w9cniBBL2GvvA54kgpQp2FapymbLwOxV8s6/ohjFnUYkWETLPE5YU3goxDFWP/fs9VO09Rlo1RS44wU2HRp4xgTpQvf0a6cGejVUUNqC+Vy1QmxUZK0p8ayT5Fp0tYUJgV9WGNzSjM6A9g+GxnwVA=,iv:kRsp+yB4K4IKohHZx2OMoeClPIHJDjcg5v5lWV6WMTg=,tag:s/GjrK0JRdl7E1XuAdQy5Q==,type:str]
    pgp:
        - created_at: "2026-01-16T17:26:33Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA8zGTYfuBl06ARAAgY6xjiOCco4EH1m2Kv4wQm6muCXI+tHRPjCk6kOAeeUl
            BT7HQWgQcyxqu2m/7I8rziPpPHSXBAiQOb5m/GN4GhUSQNUVa5OfGDi0HbE3j/y9
            FATi0rpPLca9N245d0cI10oI6NcIW/ucLlDUU+dSGGbTwImGKNBkcT4dWvQn7/bx
            wzJMzahRpZSLuhThrI7mTtZYOKaqlzXZXBDSJq64jSxe7LkQnKy88xe4ZBFuV+Sn
            ncESwG07L2EXo2TgQ7VVphmqYFDusjqGnYcXXWEUxbIJrXWUuLGmHxtfJvc+Db+w
            1Kst53OTQ5NOxXpUs9WXD950UglNBBipiv9365+d7PPo7Yiu78h7CG9OKW9FOdiE
            zDcbh+usD0uWLeRxxTo+NGqyM0muPRKaUBc1rUN0FovLqnD/bPsg44cCbHKO3kV4
            DvonIGP8NMAAqCSel7gYhaiaYcETK3+egAbHD+2b7jNYH/waoa5tAMMUqw5LJml8
            PbJrRXZt68vbPSVZ5waWyUtXWYHdaaQuMoQnLJsZoBP7Uj3I8gqGzuZBGk0ePgl0
            CUufXT5YSw9QX7SO027OV8qDE1++CZKc1TMxk9DYNfFMcKxiLdJFYCWg6yYnqqHI
            fp6mOScjkiXr9kM1CY0SctcAJaeyA3eG55iyW+9DveY1VqyKZzC9pz2RtAhr9kfU
            aAEJAhCHARarbJlvpf0sM1fOy9DlGS16L4sh1OrYmtJN8D9rYXGKwGIDQ4BYgRew
            rjIQrUj2NW/SA3X3bYEOQhKUgtfSy72x/jX3o7Q5LBJvOJXl5654KGGkublAmGpT
            bZSFmC+6n+RS
            =BNl2
            -----END PGP MESSAGE-----
          fp: 51DECC40A0CA13D21FA6FCF3775783D61292D91E
    unencrypted_suffix: _unencrypted
    version: 3.11.0
