apiVersion: ENC[AES256_GCM,data:mzo=,iv:4N5iMXk3NIb29iRQ1W2ZO74wRdPe+THQCH8CQ1B2mRg=,tag:EAAHe2CtBxtBCavzfHgFJg==,type:str]
kind: ENC[AES256_GCM,data:Hd+8Wc3m,iv:nAibWQlRC/YPB/So+IwVwW/Sz25RNI5SOwuds4qltI8=,tag:bUk7KeqeBokB3hpDZOTx3w==,type:str]
data:
    password: ENC[AES256_GCM,data:LjZcOlcyFh4py5c1fH30vw==,iv:uc9eagTI8mvpvqLSI3k/AJLZKo5P3qf7xLbXBrCoD2g=,tag:DlhVvZqRWYLqXWtmUHV2UQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:W3WiWc7LUjhrbiX1Gg==,iv:MIoSyztX3ZmOIKUIDyXmOotChuPmuubyDEjtGh0LFXQ=,tag:oDjIH9yGsecB7A1qd9jPLw==,type:str]
    namespace: ENC[AES256_GCM,data:ob+CTRUDF1UIkDE=,iv:+5xVOzgQE1J1FdI07MSGvT9g7VQSF1QTunVVRBe6kK4=,tag:hq5lWPpyq056O/6mvlcejQ==,type:str]
type: ENC[AES256_GCM,data:zwNsoZjS,iv:lugBmSE86jg+SRkpBdVV2eEVezmeahbDJHZqo05MNKc=,tag:c8sKJ2fbRhEE1pD2osyhhA==,type:str]
sops:
    lastmodified: "2026-01-16T22:28:59Z"
    mac: ENC[AES256_GCM,data:OG+FTHMqhDnjvIeeTrwNRkP2i/SbkF97/4K5qC1aBiVxd1U7/NIKC2fkpniQ4Zoj5M2Kqu1D5yX9J9xnSPxtQ0MoL5XH95lK6NENrx4cbvjgnA/nQxEMlrtLrRFSMYTQTdxxLZiZzfYJDP3azTffEc48QSxFg+V8R71PmHgxQEY=,iv:PhfV3wNbBVD5KsqdxKsu/4bo9YTL4Ot39nftm4jdJ3M=,tag:zXtnOACxyzzinxcRMvjiKA==,type:str]
    pgp:
        - created_at: "2026-01-16T22:28:59Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA8zGTYfuBl06ARAA0lvvAuApNT+MFP/yB3leG5KcYrN3KYtLZ/JCKVjp7wC0
            YRH4H9mWHKqO/AQPzhvqcBCEF1WbNtowtnI1tPULSuZ9+ipUm0IBYMCZ8zq+mHHB
            INmRF/1YVYK41B0FDYaGGhvF2yGHa1AEixq8zKfq75hDvYNBg055uRgMYl47/nR6
            s9v3FSoC5vDAk7CiXWP3I4pfJXa1HKg98zMVBjkJvDYKg6xtWu2rp2StF43fOxX6
            X/O/XvXGsViVs5JUH/QXMeoYMoi9X/tCyUtEfepedMGyT1T64sTR1eVSLE590SaS
            1zBOO4zQFVmzvz9MukZ9KFLHCs4G5DvNW0P/UsZWhOWpdrhyrwPdNEecKnn82gc+
            iZ6MQPF2e7U3tc9YKsTHr3xmUlfbEi1SYR5A2GkY0MLtCpBkq2KzEWGS5ueEkUTn
            ZPiNfeqeTiCgY1mcx+l95gqPopVYzenWg7v8b22YtiR17f5v450xSLoms+CoSekC
            FAwOCEm+DYbGU+rr1bQnaSpb0tBoWx1NusMWZgA+GM36yeoY+5t5gDbVfiupfHcE
            v/Qx7e6n/bIhmYFNQyti1MF++pj/OS8JhDkctB3CtiSCJpJPl8l6MuBBcmvvzELy
            MNMvxbqQRE/e8H+jbk105zw3leP36IDyIuQi6ad7UJUc9efxkxLB4smzxRqBy3zU
            aAEJAhDKlAk/4a5QQa9cA+lxR+9BSCGMb2TJtxlpnnxtfOUKBA5bmWMEDk35zaH8
            lud6CV/mqi4IuKnlxeVVMS9OWD6ID8xOAJiUb7o5SO9xfBVu/0DMHaarrlj5IwCo
            9dJha+sQK7ht
            =evBX
            -----END PGP MESSAGE-----
          fp: 51DECC40A0CA13D21FA6FCF3775783D61292D91E
    unencrypted_suffix: _unencrypted
    version: 3.11.0
