apiVersion: v1
kind: Namespace
metadata:
  name: step-ca
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: step-ca
  namespace: step-ca
spec:
  interval: 30m
  chart:
    spec:
      chart: step-certificates
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: smallstep
        namespace: flux-system
      version: "1.29"
  values:
    inject:
      enabled: true
      # Config contains the configuration files ca.json and defaults.json
      config:
        files:
          ca.json:
            root: /home/step/certs/root_ca.crt
            federateRoots: []
            crt: /home/step/certs/intermediate_ca.crt
            key: /home/step/secrets/intermediate_ca_key
            address: :9000
            dnsNames:
              - step-ca-step-certificates.step-ca.svc.cluster.local
              - 127.0.0.1
            logger:
              format: json
            db:
              type: badgerv2
              dataSource: /home/step/db
            authority:
              enableAdmin: false
              provisioners:
                - {
                    "type": "JWK",
                    "name": "admin",
                    "key":
                      {
                        "use": "sig",
                        "kty": "EC",
                        "kid": "dXt6Rp1Ow0uFiSTd-We-YYUKZFuU26TBy39-mKxmkdo",
                        "crv": "P-256",
                        "alg": "ES256",
                        "x": "Nj6JXUsYn0qsj5YHkSjrPv9oVesESlB8aAUXSwHfmPw",
                        "y": "4Z2BilMkb7zrizX-qOa9iX_8zAwXOpQhkFMXitoJLIs",
                      },
                    "encryptedKey": "eyJhbGciOiJQQkVTMi1IUzI1NitBMTI4S1ciLCJjdHkiOiJqd2sranNvbiIsImVuYyI6IkEyNTZHQ00iLCJwMmMiOjYwMDAwMCwicDJzIjoiM3ptNlBJUTZGN2g5SzF2SExhQjhodyJ9.Cj2RKfAxLhp_FOTAiQ9z2vkXIhihqU47k2RhoT_o8hJ2JoiCUaY0MQ.RbqpY5e1kdy093FB.Kz8e-ML97iqwfNaSKx8RJHSfFWhnDkRX2pd9ItpaZXA29EtvKnqOnoM55HaQ2bNovv3zOTvwgzYZKHNk4acLuBRSSaXS34Nd-8KLOgl72wDHCVHr7db6ycSK4yXVXQARSzabCLjlw532sstRiSnd6rXe0wM-UfGVerJAyYjioG0YIgG4S7YRPtH9voTLYtBtKobx6ZJ9FFlATdyxKMVLR-O8E7MzP29NLFojKV8uesras2JqxQM_OtCVB4b309nAJbESvyfrbMzf0WwTmTCsnW_njgbrxKuPfJI8GEIIcvJP2-n2g5EXi3dPyMutox62EJLbJzdI0T52QX5UakE._cHN6FICSrSsygC3U8k-bA",
                    "options": { "x509": {}, "ssh": {} },
                  }
                - type: ACME
                  name: acme
            tls:
              cipherSuites:
                - TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256
                - TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
              minVersion: 1.2
              maxVersion: 1.3
              renegotiation: false

          defaults.json:
            ca-url: https://step-ca-step-certificates.step-ca.svc.cluster.local
            ca-config: /home/step/config/ca.json
            fingerprint: d36a965e54431b082d6cd7be84784c698a9f7ccbf5e5c989642b138e3190e3bc
            root: /home/step/certs/root_ca.crt

      # Certificates contains the root and intermediate certificate and
      # optionally the SSH host and user public keys
      certificates:
        # intermediate_ca contains the text of the intermediate CA Certificate
        intermediate_ca: |
          -----BEGIN CERTIFICATE-----
          MIIB0TCCAXagAwIBAgIQBDvJMY7WiOJe6XS3/mey2DAKBggqhkjOPQQDAjAyMRMw
          EQYDVQQKEwpDQS1Ib21lbGFiMRswGQYDVQQDExJDQS1Ib21lbGFiIFJvb3QgQ0Ew
          HhcNMjYwMTA4MDAxODU2WhcNMzYwMTA2MDAxODU2WjA6MRMwEQYDVQQKEwpDQS1I
          b21lbGFiMSMwIQYDVQQDExpDQS1Ib21lbGFiIEludGVybWVkaWF0ZSBDQTBZMBMG
          ByqGSM49AgEGCCqGSM49AwEHA0IABDD0qIykoAHfkj2YasDq+Gsl67ybhOD8IxO/
          F9a6XKfZz2FA0pbTAQ2UgzX17vmXv3cglAZBUZsR68R5EZ3vUVejZjBkMA4GA1Ud
          DwEB/wQEAwIBBjASBgNVHRMBAf8ECDAGAQH/AgEAMB0GA1UdDgQWBBTNzAClrgiC
          dcrLZCVXfLAthaP6ATAfBgNVHSMEGDAWgBQNdoV0tgd9/1nnPl6Cci3/6gqXKjAK
          BggqhkjOPQQDAgNJADBGAiEAzhWeXxipNv30JvAn8NimiYYH6zMX2KVl5XhPW0Sz
          uhkCIQCJWvEQJXcZ43KlKm9B60DiEPplP5CN9vk7xVZTbVz92w==
          -----END CERTIFICATE-----

        # root_ca contains the text of the root CA Certificate
        root_ca: |
          -----BEGIN CERTIFICATE-----
          MIIBqTCCAU6gAwIBAgIRAJ3DDtw0tSoMweSBfRCj2qcwCgYIKoZIzj0EAwIwMjET
          MBEGA1UEChMKQ0EtSG9tZWxhYjEbMBkGA1UEAxMSQ0EtSG9tZWxhYiBSb290IENB
          MB4XDTI2MDEwODAwMTg1NVoXDTM2MDEwNjAwMTg1NVowMjETMBEGA1UEChMKQ0Et
          SG9tZWxhYjEbMBkGA1UEAxMSQ0EtSG9tZWxhYiBSb290IENBMFkwEwYHKoZIzj0C
          AQYIKoZIzj0DAQcDQgAEDtxFW2oLSnhpFmIEWOhlCGRprvmg2dcFTDbaoUiSkQkx
          1FU/DtEKG6V4Q3CgXFoluDPoz2T4pd/goDJqVp1cJaNFMEMwDgYDVR0PAQH/BAQD
          AgEGMBIGA1UdEwEB/wQIMAYBAf8CAQEwHQYDVR0OBBYEFA12hXS2B33/Wec+XoJy
          Lf/qCpcqMAoGCCqGSM49BAMCA0kAMEYCIQCaqLJgRe/Df3nv04+Al09O48tjMoFJ
          tb0rbwfQ+9RUMQIhAMrZHUohHqMW4pRcdCi6wDicbYp+rVgmLZ8eV7cJSOS9
          -----END CERTIFICATE-----

  valuesFrom:
    - kind: Secret
      name: step-ca-secrets
      valuesKey: values.yaml
