apiVersion: v1
kind: Namespace
metadata:
  name: step-ca
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: step-ca
  namespace: step-ca
spec:
  interval: 30m
  chart:
    spec:
      chart: step-certificates
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: smallstep
        namespace: flux-system
      version: "1.29"
  values:
    inject:
      enabled: true
      # Config contains the configuration files ca.json and defaults.json
      config:
        files:
          ca.json:
            root: /home/step/certs/root_ca.crt
            federateRoots: []
            crt: /home/step/certs/intermediate_ca.crt
            key: /home/step/secrets/intermediate_ca_key
            address: :9000
            dnsNames:
              - ca.homelab.local
            logger:
              format: json
            db:
              type: badgerv2
              dataSource: /home/step/db
            authority:
              enableAdmin: false
              provisioners:
                - {
                    "type": "JWK",
                    "name": "admin",
                    "key":
                      {
                        "use": "sig",
                        "kty": "EC",
                        "kid": "h7CXYbIzh4T1lYVXiSnMPGRtT9uyrLU_p2ae_9N5h3E",
                        "crv": "P-256",
                        "alg": "ES256",
                        "x": "KkZCuLkiVdjFPiP33FspothOtnJiw3nA6va_bULoMXI",
                        "y": "9NZu0F0tIwDUw5MzpiCpJWvgr8SMu93pKi4ExFoDuvE",
                      },
                    "encryptedKey": "eyJhbGciOiJQQkVTMi1IUzI1NitBMTI4S1ciLCJjdHkiOiJqd2sranNvbiIsImVuYyI6IkEyNTZHQ00iLCJwMmMiOjYwMDAwMCwicDJzIjoiLVRobXU3MUtFeTQ5UEhpRnJzMmdOZyJ9.r5mqTHB798POOMtTlcOdkp3ey9vuHTcCTPBm-wUM0oeX_jjIfG7T4A.0LdqyMzPBjL2pTRh.6ECwc97IreUh-EzygyOhgM6yOLZ4jCdBgSdZxrXWDJk_KwTNRJW7v0j_A6rBbPOCPAnDf0eQS3SxjVJNWzrnQjaBI645KgE1J_c9as7NSx1oQ6tLTGsJB73z5dT81svZz__k6WhZlNFHDm8kykJOwZG8M-vzqxK7rq9f-M56cihdFNJEnVMdaMZM_q5VVtzd5friNkqhRW94Yw3TKXLTUiPvNCSIUUcy66qABmfxk1fCgMwoBWn3cbdxeihOFAYoVcZTkDEX5IVM8sDAgwhjbs00SLWGGo17jBiCZ96cDMy7YHSHnAdaab8JoTx00f-tI4AXjnPuHdJr2iYGYZE.A1wv_HNxQVBVCOOuGAwmfA",
                    "options": { "x509": {}, "ssh": {} },
                  }
                - type: ACME
                  name: acme
            tls:
              cipherSuites:
                - TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256
                - TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
              minVersion: 1.2
              maxVersion: 1.3
              renegotiation: false

          defaults.json:
            ca-url: https://ca.homelab.local
            ca-config: /home/step/config/ca.json
            fingerprint: adbfd8f09e7640423d3fc4e5a04bb4fb899215cc364ce12ece182c441d3420f1
            root: /home/step/certs/root_ca.crt

      # Certificates contains the root and intermediate certificate and
      # optionally the SSH host and user public keys
      certificates:
        # intermediate_ca contains the text of the intermediate CA Certificate
        intermediate_ca: |
          -----BEGIN CERTIFICATE-----
          MIIBzzCCAXagAwIBAgIQRVDpySMf8h5tlqrGp8LhkTAKBggqhkjOPQQDAjAyMRMw
          EQYDVQQKEwpDQS1ob21lbGFiMRswGQYDVQQDExJDQS1ob21lbGFiIFJvb3QgQ0Ew
          HhcNMjYwMTAxMjIxMTE1WhcNMzUxMjMwMjIxMTE1WjA6MRMwEQYDVQQKEwpDQS1o
          b21lbGFiMSMwIQYDVQQDExpDQS1ob21lbGFiIEludGVybWVkaWF0ZSBDQTBZMBMG
          ByqGSM49AgEGCCqGSM49AwEHA0IABKVKGOmrl5MiX8uvM+lK13YeFUc2lJy0kU4q
          LEfuhqU30ZHjnORs24zMgFqhHHaf7Sn/wW1Ph9j7GwOZ1qoJT/yjZjBkMA4GA1Ud
          DwEB/wQEAwIBBjASBgNVHRMBAf8ECDAGAQH/AgEAMB0GA1UdDgQWBBSVsIdjqpzo
          x1KQ6YrrVKU/TFWlzTAfBgNVHSMEGDAWgBROfu+IfySU39mSYjxjQ7PsItSuIDAK
          BggqhkjOPQQDAgNHADBEAiARNjiIsHgHc2EaF9zZMouraMvKJc4VH1oEfkMosYBK
          XwIgL7gxLC1S+TxbLEyadigW/pL5qjzFBr1nIjKyUzPPkl0=
          -----END CERTIFICATE-----

        # root_ca contains the text of the root CA Certificate
        root_ca: |
          -----BEGIN CERTIFICATE-----
          MIIBpzCCAU6gAwIBAgIRAJkmAUcqMXWbl0D0Ynl29qUwCgYIKoZIzj0EAwIwMjET
          MBEGA1UEChMKQ0EtaG9tZWxhYjEbMBkGA1UEAxMSQ0EtaG9tZWxhYiBSb290IENB
          MB4XDTI2MDEwMTIyMTExNFoXDTM1MTIzMDIyMTExNFowMjETMBEGA1UEChMKQ0Et
          aG9tZWxhYjEbMBkGA1UEAxMSQ0EtaG9tZWxhYiBSb290IENBMFkwEwYHKoZIzj0C
          AQYIKoZIzj0DAQcDQgAEZunSl/GqhiTC+cC1KFOK/7Ul155vUUcEvUkQ5/y1UlE/
          xacb7k1rXD/kcvb3lkXRI+ay69k2l3Linl9tdlwfOKNFMEMwDgYDVR0PAQH/BAQD
          AgEGMBIGA1UdEwEB/wQIMAYBAf8CAQEwHQYDVR0OBBYEFE5+74h/JJTf2ZJiPGND
          s+wi1K4gMAoGCCqGSM49BAMCA0cAMEQCIG4PYNUpyQSmXPCl+3iL9iinzbBdp/iF
          v2HPhgT0mvHFAiBgt59bzBSM1muFH4lb4G2MBkJNgVO1ykwFZaALBgvDEA==
          -----END CERTIFICATE-----

      # Secrets contains the root and intermediate keys and optionally the SSH
      # private keys
      secrets:
        # ca_password contains the password used to encrypt x509.intermediate_ca_key, ssh.host_ca_key and ssh.user_ca_key
        # This value must be base64 encoded.
        ca_password: cGFzc3dvcmQK
        provisioner_password: cGFzc3dvcmQK

        x509:
          # intermediate_ca_key contains the contents of your encrypted intermediate CA key
          intermediate_ca_key: |
            -----BEGIN EC PRIVATE KEY-----
            Proc-Type: 4,ENCRYPTED
            DEK-Info: AES-256-CBC,b23c0ced1f943186b42701cfe6aabc49

            r7OI2NbuYFkCkPXuMr9ubcH7zqHI99PtJW96dBFL/XLFqAW/Z8jsNGcp+JQgRbNu
            ugGIDWpr0qfxKTnT57indHgcf2WrdHRMuLwhfUwOspG2+y8aa5mpk55qtQ7/skbS
            X6KI6nAP5IElKyJf/FArJtLB0+kIxiCddiIjvoWyy5U=
            -----END EC PRIVATE KEY-----

          # root_ca_key contains the contents of your encrypted root CA key
          # Note that this value can be omitted without impacting the functionality of step-certificates
          # If supplied, this should be encrypted using a unique password that is not used for encrypting
          # the intermediate_ca_key, ssh.host_ca_key or ssh.user_ca_key.
          root_ca_key: |
            -----BEGIN EC PRIVATE KEY-----
            Proc-Type: 4,ENCRYPTED
            DEK-Info: AES-256-CBC,5e0b1f1ee2237cca42c6b816855581df

            X2N0a869EB6B97ZiDF2//bwtIOUQUz5Nu86dz58m8ydIHwAd461LImRjuLAuEW0H
            UNr07GsAnFtty1r7lD+rSYc0aV1NZEXbvchT5r2bI2A2sXQ9Solg4sOpMQLcAoJD
            eGtbFVUvLDTnCMTTc1jaEKIyzquh95GNXqd4vAaJ9nE=
            -----END EC PRIVATE KEY-----
