apiVersion: ENC[AES256_GCM,data:wK0=,iv:PxVx4QnCLHjW1pAXeJqVMuHgE6uryU5KhxH1Iv1pQew=,tag:l23WOEsJgQCIs/YyYcTEdA==,type:str]
kind: ENC[AES256_GCM,data:xyn2Z/zd,iv:I2PqFtpHhEqnKaAxoJcQfu5N2bQd8UsICxnQNal2+Gc=,tag:5DqUNgyHkMIxURkJm3q9sQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:sZfxkxXqLDAdQiXh8I5D,iv:uQc9YunMrL/Lr/d6qv0cwiWKAGOqO2I/QpUTy+n+qfo=,tag:rX66GQ+VkxnHDA4KyrSH8g==,type:str]
    namespace: ENC[AES256_GCM,data:yhWEuEfyNQ==,iv:a0IBNonodksche3UO5OAspLsZWV4h/pN4i/KcrD40cg=,tag:giHZIQhc+mczPVmAUCLWiw==,type:str]
stringData:
    values.yaml: ENC[AES256_GCM,data:gJxgu7ds/N6vLEhvNEOqAhggtizZhfnatuPmH6HSPcu7cKhT0WTowMTstlmN/Y9nHkzbtR5rbP6pq1SHtFkdZGcri4UCEcjBaZ8phNdVgWjSKEtslfpD7J1H+wtcEbRblkB3BATB6/hEMwNYWuCNm9zaabHK6vSw3Ux0zyTgPkBQhgVwuFISs8tnLlU2a8edO1/UaEfK2/5fp6oL7X92kWhvNovhIwMAXlOOPoW0HBd9s5/ezZPrbfWl4YVp0nQGI01VJulasqU7h2Da6arxeYhvdLtpHIhyHOBm08+eJbY6IgbugbqfIQkV/WwgF6u6q5W5ZVN9QXZ89pOWaPr/TpVGxno8lfP6M8KCOGCls9/v6yqjcBhmO3yBvLXKk7fDZG2mzj3H7j6OShVNNDNBXlBQ/NvfVJg/yg3WoyDkR3WW1BH5jpH+yWEW1f69F1QscS3LWHOEzgOaLQyVXVsX56KQFl6EdryErB9QjXYSYY9RT9p+Fnf/svlTtKov1EXhdml4PSZT9AZtQtr0cIdSrhYtOCghE1ARFMPEVcn6r4rw75Hqu4XEJgvmi4R4JxvKHF88vJddSf6m/4qDNjZqCwFm/FhGHPBjWsbR17pvKqN7jreVtjy+YWfnJDbHnNtsa0B63czT30yjXPewQPEe3L2VK3sv5vxkf6QWOROTNxO78wgDYK3/XEaIisTqlAscLMsasSJmlGrnnfhHkP3hLFcUnSS0EGDXnv2f9LIJccppWnrDf56IcvHFmVj5KxTovCUbcFEE6WsM4D0d2lJ5IWkbVfOH7ZpGiGrbXVom1MV1S4/LFKUnwO8xPWWFdRw8OlhTXmQiDRbodlT3IR/LJ8i+w7nTX1Ijy3+nieXZsPDLTdMzV66z8LMtnqFByR/9amTkiRLre0VWfIuxFUbrPjplr7884MvSs0M7ddkRXyf0OD7ebgzcDFOwyMaKVjQ5BHvJJZZyY9QB6vhscM6qEdKs8KhnC8CoUxX/KLArwXkLwOgkVS+ftbbwKeM552vlJDZpwrv6C+vCrXU/di8U5ddVn8MFP6rE7ISYV+M6rEjvqsz+XJWJjn0EZCcPAro6+DS6aGtqBfXQcSkDPwUGIUV0DcaY+Zsh1NffhldrM+05iKtg5oRZrHveo1r7YECryCpftTIT75EYgqV0jBuSljnOVamNQf7JDoL0xSf+lMkasUfwg8YPpcks6GOntVsHYzc3OLh+DRuXkac1BXm4Rph/fQwXfCtNVt/NoE8iS9CY2FGcUG2tY/vv+TRB97XbeapSlRGC6pRz+yBMp4E23Yh12vzWKeKL89SshIwgF+0ejiWCQyRn8LL5R6OL7+hDqKcsjHuZD1Isdt+f+6nGpxlBx3jX4kfJj+3+p5FDG8y5XRyQy3up3x0opGWUvJySP1kDPjd0j47qs2moWiO3Dt05JZj/hYFFkhb/H62JlAQy8iYRmvb94oBtdGw10ZIpAc0flyQjJ1thehhsatgFKTY7cwariQ+aBognBk9Zgs87b/0t56CEu3lNva2D42wk0LBeOCi6G1lGI4oeXWfJC31xAw6pIAI/faNumEMaW6WNgOYnmGVAjbLgbM2tAcFr7uTceUAPpq+i,iv:B70/lI6YHsVTYJmVzZ/BS9Ma3PSAmUYMs+YbMofJLXI=,tag:6A53CGuURZMl2d9WR2bsfQ==,type:str]
sops:
    lastmodified: "2026-01-07T21:41:18Z"
    mac: ENC[AES256_GCM,data:Eqs1Cp/1a+kZauRr8hD4SUsnLRaVqBu9kPpZ0OXsIZtqSSyC7umTb0BfCL0a5ZfQ82R8gm6Z6mSDoezJ2w6hSHxKnxCzYL7rCup2ZuR9I6iHCQu2ZjL5E62+9+1HpaGghM++UiFWXiF0RGMYIC8+5ZgruPFrKtxz5/dKge4LP/0=,iv:jzm/WONAjduObu0OLiIABu9ONDAY+XWxElFtaLCBe44=,tag:eKC1lDoLbCLFgtggcYC5pA==,type:str]
    pgp:
        - created_at: "2026-01-07T21:41:18Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA8zGTYfuBl06ARAAyTvzKZ1bREoDFKyoeO5pyKEfEb9JCM7pmnmlCwDuPpXZ
            Ns/IWLMK7zkBVodNYkA1wQlmILLJ+MkFFeE/X7FwakjUOl0zKtdFCpiB5PRZCXHK
            VbPtt6oNtS4h/m+bJd5vWUV8az8VQdqFnFjw3TOyn8gwD+iDtYcsc5mjnHNuUArz
            TCfLSW7JMj0/ndI9py+dr1YukN/Q3sYrxwzrshUgBLDyeHAbPNpDZyruxTWzUiEr
            +mdgTojK4o7cdCoYdMWOXHJrP2ECjZ34xQ3z9ZhzM9LZVa/q/bWC9f/7SaErKNXl
            aA9Dijhz6zexpn8OhWmKglL5g+p0hIKSeFK+bjlrHzWNarjRPupvNl6Iq3P0MUEC
            L7sHttY/JIaOKWKOq/1nXuhy4YMMiJXq8ckUoFN24BH5uwgJbJtcVfsW2m+cOYf9
            kR6/+MRc+evVWgfiDNFZrBTxAZ7+2UySZLof5FGoY5gPp+Qly56RpO1vAtG0bo5e
            6OxMUHlLKEooUdVdJVfK4FFxnJ783muztYvV9hA1ONjfhIWJ5DQtVCbynEGhnb7S
            SgMovItant1xEauGRRuMYLEaTY5C3hf3jmPwzYp73w1R0fXuyvuYcj1WXspt1jAe
            VofBoI8+kpAHOH1AWp835TskJePuB5AyYxXpbcls5xmKtCBqABwHiuEmVggQimjU
            aAEJAhCHoIZaw1oWFxKs6TV6pzmaICJyUCeYUZIxOW1iB9a5M5RAifmjbLAtb9aq
            4NGTEFk5kNy5RuqrsNBn4Xrpb6KRenwO+Cz9yUmFYo+afBERjXN9gBCdUvITTu9G
            2AyxY+xCel9s
            =9YGe
            -----END PGP MESSAGE-----
          fp: 51DECC40A0CA13D21FA6FCF3775783D61292D91E
    unencrypted_suffix: _unencrypted
    version: 3.10.2
