apiVersion: v1
kind: ConfigMap
metadata:
  name: step-ca-root-cert
  namespace: traefik
data:
  root_ca.crt: |
    -----BEGIN CERTIFICATE-----
       MIIBqTCCAU6gAwIBAgIRAJ3DDtw0tSoMweSBfRCj2qcwCgYIKoZIzj0EAwIwMjET
       MBEGA1UEChMKQ0EtSG9tZWxhYjEbMBkGA1UEAxMSQ0EtSG9tZWxhYiBSb290IENB
       MB4XDTI2MDEwODAwMTg1NVoXDTM2MDEwNjAwMTg1NVowMjETMBEGA1UEChMKQ0Et
       SG9tZWxhYjEbMBkGA1UEAxMSQ0EtSG9tZWxhYiBSb290IENBMFkwEwYHKoZIzj0C
       AQYIKoZIzj0DAQcDQgAEDtxFW2oLSnhpFmIEWOhlCGRprvmg2dcFTDbaoUiSkQkx
       1FU/DtEKG6V4Q3CgXFoluDPoz2T4pd/goDJqVp1cJaNFMEMwDgYDVR0PAQH/BAQD
       AgEGMBIGA1UdEwEB/wQIMAYBAf8CAQEwHQYDVR0OBBYEFA12hXS2B33/Wec+XoJy
       Lf/qCpcqMAoGCCqGSM49BAMCA0kAMEYCIQCaqLJgRe/Df3nv04+Al09O48tjMoFJ
       tb0rbwfQ+9RUMQIhAMrZHUohHqMW4pRcdCi6wDicbYp+rVgmLZ8eV7cJSOS9
       -----END CERTIFICATE-----
