apiVersion: v1
kind: ConfigMap
metadata:
  name: step-ca-root-cert
  namespace: traefik
data:
  root_ca.crt: |
    -----BEGIN CERTIFICATE-----
    MIIBpzCCAU6gAwIBAgIRAJkmAUcqMXWbl0D0Ynl29qUwCgYIKoZIzj0EAwIwMjET
    MBEGA1UEChMKQ0EtaG9tZWxhYjEbMBkGA1UEAxMSQ0EtaG9tZWxhYiBSb290IENB
    MB4XDTI2MDEwMTIyMTExNFoXDTM1MTIzMDIyMTExNFowMjETMBEGA1UEChMKQ0Et
    aG9tZWxhYjEbMBkGA1UEAxMSQ0EtaG9tZWxhYiBSb290IENBMFkwEwYHKoZIzj0C
    AQYIKoZIzj0DAQcDQgAEZunSl/GqhiTC+cC1KFOK/7Ul155vUUcEvUkQ5/y1UlE/
    xacb7k1rXD/kcvb3lkXRI+ay69k2l3Linl9tdlwfOKNFMEMwDgYDVR0PAQH/BAQD
    AgEGMBIGA1UdEwEB/wQIMAYBAf8CAQEwHQYDVR0OBBYEFE5+74h/JJTf2ZJiPGND
    s+wi1K4gMAoGCCqGSM49BAMCA0cAMEQCIG4PYNUpyQSmXPCl+3iL9iinzbBdp/iF
    v2HPhgT0mvHFAiBgt59bzBSM1muFH4lb4G2MBkJNgVO1ykwFZaALBgvDEA==
    -----END CERTIFICATE-----
