---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: traefik
  namespace: traefik
spec:
  interval: 1m
  chartRef:
    kind: OCIRepository
    name: traefik
    namespace: flux-system
  timeout: 10m
  install:
    disableWait: true
  upgrade:
    disableWait: true
  rollback:
    disableWait: true
  values:
    persistence:
      enabled: true
      path: /step-ca
      size: 1Gi
    certificatesResolvers:
      homelab:
        acme:
          email: admin
          caServer: https://ca.homelab.local:9000/acme/acme/directory
          storage: /step-ca/acme.json
          certificatesDuration: 72
          tlsChallenge: true
    podSecurityContext:
      fsGroup: 65532
