apiVersion: v1alpha1
kind: NetworkRuleConfig
name: ingress-pihole
# Port selector defines which ports and protocols on the host are affected by the rule.
portSelector:
  # Ports defines a list of port ranges or single ports.
  ports:
    - 53
  protocol: udp
# Ingress defines which source subnets are allowed to access the host ports/protocols defined by the `portSelector`.
ingress:
  - subnet: 10.0.0.0/16
