apiVersion: v1
kind: ConfigMap
metadata:
  name: glance-config
  namespace: default
data:
  glance.yml: |
    pages:
    - name: Home
      columns:
        - size: small
          widgets:
            - type: calendar
              first-day-of-week: monday

            - type: rss
              limit: 10
              collapse-after: 3
              cache: 12h
              feeds:
                - url: https://selfh.st/rss/
                  title: selfh.st
                  limit: 4
                - url: https://www.cloudcomputing-news.net/feed/
                - url: https://kubernetes.io/feed.xml
                  title: Kubernetes Official Blog 

        - size: full
          widgets:
            - type: group
              widgets:
                - type: hacker-news
                - type: lobsters
                  sort-by: hot
                  tags:
                    - go
                    - linux
                  limit: 15
                  collapse-after: 5

            - type: videos
              channels:
                - UCfz8x0lVzJpb_dgWm9kPVrw # The DoT 
                - UCYeiozh-4QwuC1sjgCmB92w # DevOps ToolBox
                - UCdngmbVKX1Tgre699-XLlUA # Techworld with Nana 

            - type: group
              widgets:
                - type: reddit
                  subreddit: selfhosted
                  show-thumbnails: true
                - type: reddit
                  subreddit: nba 
                  show-thumbnails: true

        - size: small
          widgets:
            - type: weather
              location: Toronto, Canada
              units: metric
              hour-format: 12h

            - type: monitor
              title: Services
              sites:
                - title: Grafana
                  url: https://grafana.homelab.local
                  allow-insecure: true 
                  icon: di:grafana
                - title: Prometheus
                  url: http://prometheus.homelab.local
                  icon: di:prometheus
                - title: Alertmanager
                  url: http://alertmanager.homelab.local 
                  icon: di:alertmanager
                - title: Pihole
                  url: https://pihole.homelab.local 
                  icon: si:pihole

            - type: markets
              markets:
                - symbol: SPY
                  name: S&P 500
                - symbol: BTC-USD
                  name: Bitcoin
                - symbol: NVDA
                  name: NVIDIA
                - symbol: AAPL
                  name: Apple
                - symbol: MSFT
                  name: Microsoft
            - type: dns-stats
              service: pihole
              url: https://pihole.homelab.local
              username: admin
