---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: traefik
  namespace: kube-system
spec:
  interval: 1m
  chartRef:
    kind: OCIRepository
    name: traefik
    namespace: kube-system
  timeout: 10m
