apiVersion: v1
kind: Namespace
metadata:
  name: rook-ceph
  labels:
    pod-security.kubernetes.io/enforce: privileged
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: rook-ceph-operator
  namespace: rook-ceph
spec:
  interval: 5m
  chart:
    spec:
      chart: rook-ceph
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: rook-release
        namespace: flux-system
      version: "v1.18.9"
  values:
    csi:
      enableCephfsDriver: false
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: rook-ceph-cluster
  namespace: rook-ceph
spec:
  interval: 5m
  dependsOn:
    - name: rook-ceph-operator
      namespace: rook-ceph
  chart:
    spec:
      chart: rook-ceph-cluster
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: rook-release
        namespace: flux-system
      version: "v1.18.9"
  values:
    cephBlockPools:
      - name: ceph-blockpool
        spec:
          replicated:
            size: 1
            requireSafeReplicaSize: false
        storageClass:
          enabled: true
          name: ceph-block
          isDefault: true
          reclaimPolicy: Delete
          allowVolumeExpansion: true
          volumeBindingMode: Immediate
    configOverride: |
      [global]
      osd_pool_default_size=1
      osd_pool_default_min_size = 1
    cephClusterSpec:
      storage:
        useAllNodes: false
        nodes:
          - name: worker1
            devices:
              - name: nvme1n1
      resources:
        mon:
          requests:
            cpu: 500m
            memory: 512Mi
      mon:
        count: 3
        allowMultiplePerNode: true
